name: Upload package

on:
  push:
    branches:
      - '**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # SDK Version to use.
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
      - run: dotnet build --configuration Release AElf.EntityMapping.sln
      - name: Create the package
        run: dotnet pack --configuration Release AElf.EntityMapping.sln
      - name: Publish the package to GPR
        run: dotnet nuget push AElf.EntityMapping.sln/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json
        